version: '3.9'

services:
  ffc-pay-event-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.16.0
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose"
    volumes:
      - azurite_data:/data
    ports:
      - "10025:10000"
      - "10026:10001"
      - "10027:10002"

volumes:
  azurite_data:
