#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

while :; do
  case $1 in
    -d|--detached)
      detached="true"
      ;;
    -v|--verbose)
      verbose="true"
      ;;
    *)
      break
  esac

  shift
done


if [ "${detached}" = "true" ]; then
  docker-compose up -d &&
    npm run start:detached
elif [ "${verbose}" = "true" ]; then
  docker-compose up -d &&
    npm run start:verbose
else
  docker-compose up -d &&
    npm run start
fi
